@startuml RedCode

namespace Engine {

namespace Entity {

    class Entity<T> {
        +const EntityTypeID getEntityTypeID() const;
        +const EntityID getEntityID() const;
        +void setEnable(bool enable);
        +bool getEnable() const;

        -bool _enabled;
        -EntityID _id;
    }

    class EntityManager {
        +EntityID createEntity<T>(args...);
        +Entity *getEntity(EntityID);
        +void destroyEntity(EntityID);
    }
}

}
